import './globals.css'
import {Header} from '../src/components/Header/Header'
import type { Metadata } from 'next'
import { Monda } from 'next/font/google'

const monda = Monda({subsets: ["latin"], weight: "400", preload: false})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={monda.className}>
        <Header />
        
        {children}</body>
    </html>
  )
}
